library(readxl)
datafix <- read_excel("Data Mining/datafix.xlsx")
View(datafix)
install.packages("arules")
install.packages("arulesViz")
library(arules)
library(arulesViz)
qq=as.matrix(datafix)
qq=as(qq,"transactions")
rules=apriori(qq,parameter=list(supp=0.2,conf=0.5,minlen=2))
rules=sort(rules, by="lift")
inspect(rules)
plot(rules,method="graph", control=list(type="itemsets"))
